services:
  db:
    container_name: fastbooks_database
    image: postgres:17
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    env_file: .env
    ports:
      - 5432:5432
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: postgres
    #   POSTGRES_DB: fastbooks

  adminer:
    container_name: fastbooks_adminer
    image: adminer:5
    restart: always
    ports:
      - 8080:8080
